logg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('loggs.urls')),
]

loggs/urls.py
"""Defines URL patterns for loggs."""

from django.urls import path

from . import views

app_name = 'loggs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # Page that show all loggs.
    path('loggs/', views.loggs, name='loggs'),

    # Page that show a single Logg and it's entries
    path('loggs/<int:logg_id>/', views.logg, name='logg'),

    # Page for adding a new logg
    path('new_logg/', views.new_logg, name='new_logg'),

    # Page for adding a new log in entry.
    path('new_log/<int:logg_id>/', views.new_log, name='new_log'),

    # Page for editing a log in entry
    path('edit_log/<int:log_id>/', views.edit_log, name='edit_log'),
    
    # Path for confirming deleteing a log in entry.
    path('delete_log/<int:log_id>/', views.delete_log, name='delete_log'),

    # Path for confirming deleting an entire Logg
    path('delete_logg/<int:logg_id>/', views.delete_logg, name='delete_logg'),

    
]

users/urls.py
"""Defines URL patterns for users."""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),

    # Confirming logout page
    path('confirm_logout/', views.confirm_logout, name="confirm_logout"),

    # Registration page
    path('register/', views.register, name="register"), 

    
]

loggs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Logg(models.Model):
    """A Logg which is a topic the user wants to Logg under."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=False)

    def __str__(self):
        """Returning a string represeentation of our model. """
        return self.text
    

class Loggs(models.Model):
    """Specific loggs which user use to document notes under their differnt Logg"""
    logg = models.ForeignKey(Logg, related_name='logs', on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'logs'

    def __str__(self):
        """Returns a string representation of the model."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

loggs/forms.py
from django import forms

from .models import Logg, Loggs

class LoggForm(forms.ModelForm):
    class Meta:
        model = Logg
        fields = ['text', 'public']
        widgets = {
            'public': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }


class LogsForm(forms.ModelForm):
    class Meta:
        model = Loggs
        fields = ['text']
        labels={'text':'Loggs:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

loggs/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotAllowed
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Logg, Loggs
from .forms import LoggForm, LogsForm

# Create your views here.

def index(request):
    """Home page for loggs."""
    if request.user.is_authenticated:
        loggs = Logg.objects.filter(owner=request.user) | Logg.objects.filter(public=True)
    else:
        loggs = Logg.objects.filter(public=True)
    context = {'loggs': loggs}

    return render(request, 'loggs/index.html', context)


def check_logg_owner(logg, user):
    if logg.owner != user:
        raise Http404

@login_required
def loggs(request):
    """Shows all logs."""
    loggs = Logg.objects.filter(owner=request.user).order_by('date_added')
    # loggs = Logg.objects.order_by('date_added')
    context = {'loggs': loggs}
    return render(request, 'loggs/loggs.html', context)

@login_required
def logg(request, logg_id):
    logg = Logg.objects.get(id=logg_id)
    # Make sure the topic belongs to the current user.
    #check_logg_owner(logg, request.user)
    

    logs = logg.logs.order_by("-date_added")
    context = {'logg': logg, 'logs': logs}
    return render(request, 'loggs/log.html', context)


@login_required
def new_logg(request):
    """Adds a new logg."""
    if request.method != 'POST':
        # No data has been sent, so create a new form
        form = LoggForm()

    else:
        # POST data has been submitted; so process and save.
        form = LoggForm(data=request.POST)
        if form.is_valid():
            new_logg = form.save(commit=False)
            new_logg.owner = request.user
            new_logg.save()
            return redirect('loggs:loggs')
        
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'loggs/new_logg.html', context)

@login_required
def new_log(request, logg_id):
    """Adds a new log under each Logg."""
    logg = Logg.objects.get(id=logg_id)
    check_logg_owner(logg, request.user)

    if request.method != 'POST':
        # No data submitted, just creates blank page. 
        form = LogsForm()

    else:
        # POST data submitted; process data
        form = LogsForm(data=request.POST)
        if form.is_valid():
            new_log = form.save(commit=False)
            new_log.logg = logg
            new_log.save()
            return redirect('loggs:logg', logg_id=logg_id)
        
    # Display a blank or invalid form. 
    context = {'logg': logg, 'form': form}
    return render(request, 'loggs/new_log.html', context)


@login_required
def edit_log(request, log_id):
    """Edit an existing log."""
    log = Loggs.objects.get(id=log_id)
    logg = log.logg
    check_logg_owner(logg, request.user)
    

    if request.method != 'POST':
        # Initial request, prefill the form with the current entry.
        form = LogsForm(instance=log)
    
    else:
        # POST data submitted; process data.
        form = LogsForm(instance=log, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('loggs:logg', logg_id=logg.id)
        
    context = {'log': log, 'logg': logg, 'form': form}
    return render(request, 'loggs/edit_log.html', context)


@login_required
def delete_log(request, log_id):
    """Deletes a single log entry."""
    log = Loggs.objects.get(id=log_id)
    logg = log.logg
    check_logg_owner(logg, request.user)

    if request.method == 'POST':
        log.delete()
        return redirect('loggs:logg', logg_id=logg.id)
    else:
        return HttpResponseNotAllowed(['POST'])


@login_required
def delete_logg(request, logg_id):
    """Deletes an entire Logg and all its logs."""
    logg = Logg.objects.get(id=logg_id)
    check_logg_owner(logg, request.user)

    if request.method == 'POST':
        logg.delete()
        return redirect('loggs:loggs')
    else:
        return HttpResponseNotAllowed(['POST'])

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm



# Create your views here.

def confirm_logout(request):
    """Render the confirmation logout page."""
    return render(request, 'registration/confirm_logout.html')

def register(request):
    """Register's a new user."""
    if request.method != "POST":
        # Display default django registration form.
        form = UserCreationForm()

    else:
        # Process the completed form for registration and login.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log in new user then redirect to home page. 
            login(request, new_user)
            return redirect('loggs:index')
        
    # Display a blank or invalid form. 
    context = {'form': form}
    return render(request, 'registration/register.html', context)

loggs/templates/loggs/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>LOGGS</title>


  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}


 
  


</head>


<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'loggs:index' %}">
        LOGGS
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span> 
      </button>
  
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'loggs:loggs' %}">Loggs</a>
          </li>
        </ul> <!-- End of links on the left side of the navbar -->
  
        <!-- Account-related links -->
        <ul class="navbar-nav ms-auto mb-2 mb-md-0">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hello, {{ user.username }}.</span>
            </li>
            <form action="{% url 'users:confirm_logout' %}" method="post" class="d-inline">
              {% csrf_token %}
              <button name="submit" class="btn btn-outline-secondary btn-sm">
                Log out
              </button>
            </form>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
            </li>
          {% endif %}
        </ul><!-- End of account-related links -->
      </div> <!-- Closes collapsible parts of the navbar -->
    </div>  <!-- Closes navbar's container -->
  </nav> <!-- End of the navbar -->
  

  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

loggs/templates/loggs/edit_log.html
{% extends "loggs/base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container mt-4">
    <h2>Edit Log</h2>

    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button name="submit" class ="btn btn-primary">Save changes</button>
    </form>
  </div>
{% endblock content %}

loggs/templates/loggs/index.html
{% extends "loggs/base.html" %}

{% block content %}

{% block page_header %}

  <div class="p-3 mb-4 bg-light border rounded-3">
    
    <div class="container-fluid py-4">
      
      <h1 class="display-3">Track your activities</h1>

      <p class="lead">Make tracking your activities easier 
        and keep a list of things you want to monitor along with your logs.</p>

      {% if not user.is_authenticated %}  
        <a class="btn btn-primary btn-lg mt-1" 
        href="{% url 'users:register' %}">Register &raquo;</a>
      {% endif %}
      
    </div>

  </div>
{% endblock page_header %}

{% if user.is_authenticated %}
<div class="container mt-4">
  <h2>Loggs</h2>

  <div class="row">
    {% for logg in loggs %}
      <div class="col-md-4 mb-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ logg.text }}</h5>
            <p class="card-text">Added on: {{ logg.date_added|date:"F j, Y" }}</p>
            <p class="card-text">Owner: {{ logg.owner.username }}</p>
            {% if logg.public %}
              <span class="badge bg-success">Public</span>
            {% else %}
              <span class="badge bg-secondary">Private</span>
            {% endif %}
              <a href="{% url 'loggs:logg' logg.id %}" class="btn btn-primary mt-2">View Logg</a>
          </div>
        </div>
      </div>
    {% empty %}
      <p class="text-muted">No loggs available.</p>
    {% endfor %}
{% endif %}
  </div>
</div>


{% endblock content %}

loggs/templates/loggs/log.html
{% extends 'loggs/base.html' %}
{% load static %}

{% block content %}

{% block page_header %}
  <h1>{{ logg.text}}</h1>
{% endblock page_header %}

<p>
  {% if logg.owner == request.user %}
      <a href="{% url 'loggs:new_log' logg.id %}">Add new log</a>
  {% endif %}
</p>
<ul>
  {% for log in logs %}
    <div class="card mb-3">
      <!-- Card header with timestamp, edit and delete link -->
      <h4 class="card-header">
        {{ log.date_added|date:'M d, Y H:i' }}
        <small>
          {% if logg.owner == request.user %}
            <a href="{% url 'loggs:edit_log' log.id %}">Edit Log</a>
          {% endif %}
        </small>
      </h4>
      <!--Card body with entry log text-->
      <div class="card-body">{{ log.text|linebreaks }}</div>
      {% if logg.owner == request.user %}
        <form class="delete-form" action="{% url 'loggs:delete_log' log.id %}" method="post" style="display:inline;">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger delete-btn">Delete Log</button>
      {% endif %}
          </form>
    </div>
  {% empty %}
    <p>There are no entries for this Logg yet.</p>
  {% endfor %}
</ul>
<p>
  {% if logg.owner == request.user %}
      <form class="delete-form" action="{% url 'loggs:delete_logg' logg.id %}" method="post" style="display:inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger delete-btn">Delete Logg</button>
      </form>
  {% endif %}
</p>



{% endblock content %}


{% block extra_js%}
<script src="{% static 'js/delete_logs.js' %}"></script>
{% endblock extra_js %}

loggs/templates/loggs/loggs.html
{% extends "loggs/base.html" %}

{% block content %}

{% block page_header %}

  <h1>LOGGS</h1>

{% endblock page_header %}

  <ul class="list-group border-bottom pb-2 mb-4">
    {% for logg in loggs %}
      <li class="list-group-item border-0">
        <a href="{% url 'loggs:logg' logg.id%}">{{ logg.text }}</a>
      </li>
    {% empty %}
      <li class="list-group-item border-0">No Loggs have been entered yet</li>
    {% endfor %}
  </ul>

  <a href="{% url 'loggs:new_logg' %}">Add a new logg</a>

{% endblock content %}

loggs/templates/loggs/new_log.html
{% extends "loggs/base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container mt-4">
  
    <h2>New Log</h2>
    <p>Add a new log for your Logg: <strong>{{ logg }}</strong></p>

    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-primary">Add new log</button>
    </form>
  </div>

{% endblock content %}

loggs/templates/loggs/new_logg.html
{% extends "loggs/base.html" %}
{% load django_bootstrap5 %}
{% load widget_tweaks %}

{% block content %}
  <div class="container mt-4">
    <h2>Add a new Logg</h2>

    <form method="post">
    {% csrf_token %}
    <!-- Render all fields except 'public' -->
    {% for field in form %}
      {% if field.name != 'public' %}
        {% bootstrap_field field %}
      {% endif %}
    {% endfor %}
  
    <!-- Manually render the 'public' field -->
    <div class="form-check">
      {{ form.public|add_class:"form-check-input" }}
      <label class="form-check-label" for="{{ form.public.id_for_label }}">
        Public
      </label>
    </div>
  
    <button type="submit" class="btn btn-primary">Add Logg</button>
    </form>
  </div>
{% endblock content %}